;
; Call Detail Record (CDR) Configuration
;

[general]
; Enable CDR
enable=yes

; Don't post CDRs for unanswered calls
unanswered=no

; End CDR before "h" extension
endbeforehexten=no

; Batch mode (write CDRs to database in batches)
batch=no
