;
; HTTP Media Cache Configuration
;
; Cache remote media files (sound files) locally

[general]
; Base cache directory
;cachedir=/var/cache/asterisk/media

; Default cache timeout (seconds)
;timeout=3600
