;
; UDPTL Configuration (for T.38 Fax)
;

[general]
; UDPTL port range
udptlstart=4000
udptlend=4999

; Use redundancy for error correction
udptlfecrec=yes

; Use redundancy for transmission
udptlfecspan=3

; Verbose T.38 debugging
;t38faxudptldebug=yes
